productpage:
  namespace: student19-bookinfo-dev
  image: ghcr.io/fyefee/bookinfo-productpage
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8083
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.dev.opsta.net
  path: "/student19/productpage(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  REVIEWS_HOSTNAME: http://bookinfo-dev-reviews:8082
  RATINGS_HOSTNAME: http://bookinfo-dev-ratings:8080
  DETAILS_HOSTNAME: http://bookinfo-dev-details:8081